=== bethel-school-of-technology/team-coding-knights-frontend/schema/contractor_page_schema.json
{
	"definitions": {},
	"$schema": "https://json-schema.org/draft-07/schema#", 
	"$id": "#contractor_page", 
	"title": "Contractor Page", 
	"description": "This is data points used in generating a standarized contractor page",
	"type": "object",
	"required": [
		"title",
		"contractor",
		"description",
		"images",
		"uuid",
		"updated",
		"created"
	],
	"properties": {	
		"uuid": {
			"description": "A UUID V4 that is used as page id",
			"$ref": "./user_schema.json#/definitions/UUID"
		},	
		"created": {
			"readOnly": true,
			"$id": "#contractor_page/created",
			"type": "string",
			"title": "Created",
			"description": "When the contractor created the page, created by server",
			"format": "date"
		},
		"updated": {
			"readOnly": true,
			"$id": "#contractor_page/updated",
			"type": "string",
			"title": "Created",
			"description": "When the contractor updated the page, handled by server",
			"format": "date-time"
		},
		"title": {
			"$id": "#contractor_page/title", 
			"title": "Title", 
			"type": "string",
			"default": "",
			"examples": [],
			"pattern": "^.*$"
		},
		"contractor": {
			"$ref": "./user_schema.json"
		},
		"description": {
			"$id": "#contractor_page/description", 
			"title": "Description", 
			"type": "string",
			"default": "",
			"examples": [],
			"pattern": "^.*$"
		},
		"images": {
			"$id": "#contractor_page/images", 
			"title": "Images", 
			"type": "array",
			"items": {
				"type": "string",
				"format": "iri"
			},
			"default": []
		}
	}
}

=== bethel-school-of-technology/team-coding-knights-frontend/schema/examples/page.json
{
    "$schema": "../contractor_page_schema.json",
    "uuid": "873de6f3-e309-41eb-96fa-0780297fcf60",
    "description": "string",
    "title": "string",
    "contractor": {
        "uuid": "da4cfd8d-f522-4816-8615-f71be48971c9",
        "name": "Contracter name",
        "user_type": "contractor",
        "contact": {
            "email": "email@exmaple.com",
            "tel": null,
            "website": null
        },
        "updated": "2019-10-12T07:20:50.52Z",
        "created": "2019-10-12T07:20:50.52Z"
    },
    "images": [
        "/world/docs.webp"
    ],
    "updated": "2019-10-12T07:20:50.52Z",
    "created": "2019-10-12"
}
