=== bethel-school-of-technology/team-coding-knights-frontend/schema/user_schema.json
{      
    "$schema": "https://json-schema.org/draft-07/schema#", 
	"$id": "#user", 
    "definitions": {
        "UUID": {
            "readOnly": true,
            "title": "UUID",
            "$id": "#root/uuid",
            "type": "string",
            "format": "uuid",
            "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
            "$comment": "In 2019-09, format uuid is compat with Java builtin uuid object",
            "description": "A UUID V4 seperated with hyphins"
        }
    },
	"title": "User", 
	"description": "User Object",
	"type": "object",
	"required": [
        "uuid",
        "created",
        "updated",
        "name",
        "contact",
        "user_type"
    ],
    "properties": {
        "user_type": {
            "type": "string",
            "enum": ["admin","contractor","client"],
            "title": "User Type"
        },
        "uuid": {
            "$id": "#user/uuid",
            "$ref": "#/definitions/UUID"
        },
        "created": {
            "readOnly": true,
            "$id": "#user/updated",
            "title": "Created",
            "type": "string",
            "format": "date-time",
            "description": "The date and time of when this user was created, generated by server"
        },
        "updated": {
            "readOnly": true,
            "$id": "#user/updated",
            "title": "Updated",
            "type": "string",
            "format": "date-time",
            "description": "The date and time of when this user was last updated, updated by server"
        },
        "name": {
            "$id": "#user/name",
            "title": "Name",
            "type": "string",
            "description": "This name of contractor or user"
        },
        "contact": {
            "$id": "#user/contact",
            "type": "object",
            "required": [
                "email",
                "tel",
                "website"
            ],
            "properties": {
                "email": {
                    "$id": "#user/contact/email",
                    "title": "Email",
                    "type": "string",
                    "format": "email",
                    "description": "Contractor email"
                },
                "tel": {
                    "$id": "#user/contact/tel",
                    "title": "Phone",
                    "type": ["string","null"],
                    "format": "phone",
                    "description": "contractor phone"
                },
                "website": {
                    "$id": "#user/contact/website",
                    "title": "Website",
                    "type": ["string","null"],
                    "format": "iri",
                    "description": "Contractor website"
                }
            }
        }
    }
}

=== bethel-school-of-technology/team-coding-knights-frontend/schema/examples/user.json
{
    "$schema": "../user_schema.json",
    "uuid": "da4cfd8d-f522-4816-8615-f71be48971c9",
    "updated": "2019-10-12T07:20:50.52Z",
    "created": "2019-10-12T07:20:50.52Z",
    "name": "Contracter name",
    "user_type": "contractor",
    "contact": {
        "email": "collin_blosser@yahoo.com",
        "tel": null,
        "website": null
    }
}
